# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.registry.co/co/status_registered.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.registry.co.rb'

describe Whois::Parsers::WhoisRegistryCo, "status_registered.expected" do

  subject do
    file = fixture("responses", "whois.registry.co/co/status_registered.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#domain" do
    it do
      expect(subject.domain).to eq("google.co")
    end
  end
  describe "#status" do
    it do
      expect(subject.status).to eq(["clientTransferProhibited https://icann.org/epp#clientTransferProhibited"])
    end
  end
  describe "#available?" do
    it do
      expect(subject.available?).to eq(false)
    end
  end
  describe "#registered?" do
    it do
      expect(subject.registered?).to eq(true)
    end
  end
end
