# This file is autogenerated. Do not edit it manually.
# If you want change the content of this file, edit
#
#   /spec/fixtures/responses/whois.nic.es/es/response_unavailable_ip_authorisation.expected
#
# and regenerate the tests with the following rake task
#
#   $ rake spec:generate
#

require 'spec_helper'
require 'whois/parsers/whois.nic.es.rb'

describe Whois::Parsers::WhoisNicEs, "response_unavailable_ip_authorisation.expected" do

  subject do
    file = fixture("responses", "whois.nic.es/es/response_unavailable_ip_authorisation.txt")
    part = Whois::Record::Part.new(body: File.read(file))
    described_class.new(part)
  end

  describe "#response_unavailable?" do
    it do
      expect(subject.response_unavailable?).to eq(true)
    end
  end
end
